Repository FRONTENDBOOTCAMP-11th/againSpring_shop, pull requests merged in 2025-01, with the labels that each got.

#26 [Feature] 장바구니 페이지 - 마크업 작성
  public/images/Cart1.png
  src/App.jsx
  src/index.css
  src/pages/Cart.jsx
Labels: feature, P1

#30 [REFACTOR, FIX] Header,Footer 여백 수정, index.css 중복코드 수정
  src/components/Header.jsx
  src/index.css
Labels: enhancement, refactor

#31 [Feature] routes 모듈화 작업
  package-lock.json
  package.json
  src/App.jsx
  src/components/Layout.jsx
  src/pages/Home.jsx
  src/pages/Slider.jsx
  src/pages/mainLayout.jsx
  src/routes/homeRoutes.jsx
  src/routes/index.jsx
Labels: enhancement, feature

#35 [Feature] 메인페이지 - 첫화면 구성 [슬라이드]
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/components/ProductList.jsx
  src/components/Slider.jsx
  src/components/layouts/Footer.jsx
  src/components/layouts/Header.jsx
  src/components/layouts/index.jsx
  src/pages/About.jsx
  src/pages/Home.jsx
  src/pages/mainLayout.jsx
  src/routes/homeRoutes.jsx
Labels: enhancement, feature, P1

#36 파일 경로 및 구조 변경, 슬라이드 및 메뉴 스타일, 푸터 수정
  src/App.jsx
  src/components/layouts/Footer.jsx
  src/components/layouts/Header.jsx
  src/components/layouts/index.jsx
  src/pages/Home.jsx
  src/pages/Slider.jsx
  src/pages/mainLayout.jsx
  src/routes/homeRoutes.jsx
Labels: bug, enhancement

#44 [Feature] 메인페이지 - 첫화면 구성 [상품 목록] / Header, Footer 크기 통일화
  public/images/Banner-test1.png
  public/images/Banner-test2.png
  public/images/Banner-test3.png
  src/components/Header.jsx
  src/components/ProductList.jsx
  src/components/Slider.jsx
  src/components/layouts/Footer.jsx
  src/components/layouts/Header.jsx
  src/components/layouts/Menu.jsx
  src/components/layouts/menuIcon.jsx
  src/pages/MainProducts.jsx
  src/pages/Slider.jsx
  src/routes/homeRoutes.jsx
Labels: enhancement, feature, P1

#47 Feature/9 notice markup/oh daseul
  package-lock.json
  package.json
  src/assets/images/notice/alignCenter.png
  src/assets/images/notice/alignLeft.png
  src/assets/images/notice/alignRight.png
  src/assets/images/notice/bold.png
  src/assets/images/notice/camera.png
  src/assets/images/notice/italic.png
  src/assets/images/notice/list.png
  src/assets/images/notice/underlined.png
  src/components/layouts/Header.jsx
  src/pages/notice/EditPostPage.jsx
  src/pages/notice/ListItem.jsx
  src/pages/notice/ListPage.jsx
  src/pages/notice/NewPostPage.jsx
  src/pages/notice/PostDetailPage.jsx
  src/pages/user/Login.jsx
  src/routes/homeRoutes.jsx
Labels: feature

#52 Q&A 마크업 완료
  src/assets/images/notice/alignCenter.png
  src/assets/images/notice/alignLeft.png
  src/assets/images/notice/alignRight.png
  src/assets/images/notice/bold.png
  src/assets/images/notice/camera.png
  src/assets/images/notice/italic.png
  src/assets/images/notice/list.png
  src/assets/images/notice/underlined.png
  src/components/layouts/Menu.jsx
  src/index.css
  src/pages/notice/NoticeEditPostPage.jsx
  src/pages/notice/NoticeListItem.jsx
  src/pages/notice/NoticeListPage.jsx
  src/pages/notice/NoticeNewPostPage.jsx
  src/pages/notice/NoticePostDetailPage.jsx
  src/pages/qna/ProductQnAEditPostPage.jsx
  src/pages/qna/ProductQnAPostDetailPage.jsx
  src/pages/qna/QnAEditPostPage.jsx
  src/pages/qna/QnAListItem.jsx
  src/pages/qna/QnAListPage.jsx
  src/pages/qna/QnANewPostPage.jsx
  src/pages/qna/QnAPostDetailPage.jsx
  src/pages/qna/QnAProductModal.jsx
  src/routes/homeRoutes.jsx
  vite.config.js
Labels: feature

#54 상세페이지 마크업 다시 pr
  package-lock.json
  package.json
  src/pages/Detail.jsx
  src/pages/Shop.jsx
  src/routes/homeRoutes.jsx
Labels: feature

#59 [Enhancement] 메인페이지 - 첫화면 구성 [additional]
  api/bruno-sample/againSpring/04.관리자/01.회원 관리/회원 목록 조회(미승인 회원).bru
  api/bruno-sample/againSpring/04.관리자/01.회원 관리/회원 정보 수정(판매회원 승급 승인).bru
  api/bruno-sample/againSpring/04.관리자/01.회원 관리/회원 정보 수정(판매회원 승인).bru
  api/bruno-sample/againSpring/04.관리자/02.코드 관리/코드 등록(ILB).bru
  api/bruno-sample/againSpring/04.관리자/02.코드 관리/코드 등록(joinState).bru
  api/bruno-sample/againSpring/04.관리자/02.코드 관리/코드 등록(tripTheme).bru
  api/bruno-sample/againSpring/04.관리자/02.코드 관리/코드 등록.bru
  api/bruno-sample/againSpring/04.관리자/02.코드 관리/코드 삭제.bru
  api/bruno-sample/againSpring/04.관리자/02.코드 관리/코드 수정.bru
  public/icons/plus.svg
  src/components/layouts/Menu.jsx
  src/index.css
  src/pages/InfoSection.jsx
  src/pages/MainContentSection.jsx
  src/pages/MainProducts.jsx
  src/pages/Slider.jsx
  src/routes/homeRoutes.jsx
Labels: enhancement

#68 [Feature] 메인 페이지 상태 관리 및 기능 구현 - Shop 상품 랜더링 구현 (1차)
  src/pages/Shop.jsx
Labels: feature, P1

#72 Shop.jsx에서 Detail.jsx로 이미지 호출이 안되던 현상 해결
  src/pages/Detail.jsx
Labels: bug

#82 [Feature] 상품페이지 페이지네이션 기능 구현
  src/pages/Shop.jsx
Labels: feature, P1

#84 [Feature] 탄소 발자국 페이지 구현 (초안)
  jsconfig.json
  src/components/layouts/Menu.jsx
  src/hooks/useTanso.js
  src/pages/tanso/tanso-main.jsx
  src/routes/homeRoutes.jsx
  src/store/tansoStore.js
Labels: feature, P3

#85 [Feature] Q&A 게시판 기능 구현
  src/constants/editorConfig.js
  src/hooks/useAxiosInstance.js
  src/hooks/useQnAEditPost.js
  src/pages/Detail.jsx
  src/pages/comment/CommentList.jsx
  src/pages/comment/CommentListItem.jsx
  src/pages/comment/CommentNew.jsx
  src/pages/qna/ProductQnAEditPostPage.jsx
  src/pages/qna/ProductQnAPostDetailPage.jsx
  src/pages/qna/QnAEditPostPage.jsx
  src/pages/qna/QnAListItem.jsx
  src/pages/qna/QnAListPage.jsx
  src/pages/qna/QnANewPostPage.jsx
  src/pages/qna/QnAPostDetailPage.jsx
  src/pages/qna/QnAProductModal.jsx
  src/pages/user/Login.jsx
  src/routes/homeRoutes.jsx
  src/store/qnaProductSearchStore.js
  src/utils/imageUpload.js
  vite.config.js
Labels: feature, P1

#92 [Feature] 장바구니 페이지 - 장바구니 기능
  api/bruno-sample/againSpring/02.일반 회원/04.장바구니/장바구니 상품 목록 조회(로그인 상태).bru
  api/bruno-sample/againSpring/02.일반 회원/04.장바구니/장바구니 상품 목록 조회(비로그인 상태).bru
  src/components/layouts/menuIcon.jsx
  src/hooks/useAxiosInstance.js
  src/pages/Cart.jsx
  src/routes/homeRoutes.jsx
  src/store/cartStore.js
Labels: feature, P1

#97 [Feature] 장바구니 페이지 - 위시리스트 마크업
  src/pages/Cart.jsx
  src/pages/WishList.jsx
  src/store/wishlistStore.js
Labels: feature, P2

#100 [Feature] 상품페이지 상품 필터링 기능 구현/ 상품개수 초기화 및 증감기능 구현
  package-lock.json
  package.json
  src/pages/Detail.jsx
  src/pages/Shop.jsx
Labels: feature, P1

#102 [Feature] 메인 페이지 상태 관리 및 기능 구현 - 검색기능
  src/pages/searchPage.jsx
  src/routes/homeRoutes.jsx
Labels: feature

#105 [Feature] 위시리스트 기능 추가
  src/pages/WishList.jsx
  src/store/cartStore.js
  src/store/wishlistStore.js
Labels: feature, P2

#108 [Feature] 메인 페이지 상태 관리 및 기능 구현 - 메인 상품 랜더링 및 게시판 피드 호출
  api/dbinit-sample/againSpring/data.js
  src/pages/InfoSection.jsx
  src/pages/MainProducts.jsx
  src/pages/tanso/tanso-main.jsx
  src/routes/homeRoutes.jsx
Labels: feature

#114 [Feature] 구매 버튼 컴포넌트화 작업
  src/components/PurchaseButton.jsx
  src/pages/Cart.jsx
  src/pages/WishList.jsx
  src/store/cartStore.js
  src/store/purchaseStore.js
Labels: feature, P1

#117 [Fix] 구매 오류 수정
  src/store/purchaseStore.js
Labels: bug, P1

#118 [Feature] 게시판 이전글/다음글 네비게이션 기능 구현 외 ..
  public/images/notice-list-img.png
  src/pages/notice/NoticeListItem.jsx
  src/pages/notice/NoticeListPage.jsx
  src/pages/notice/NoticePostDetailPage.jsx
  src/pages/qna/QnAListPage.jsx
  src/pages/qna/QnAPostDetailPage.jsx
  src/pages/qna/QnAProductModal.jsx
Labels: feature, P2

#125 상품관리페이지와 상세페이지 연결 기능 구현/ 이미지 출력 오류 해결
  src/pages/Shop.jsx
Labels: bug, feature

#126 [Refactor] 게시판 리팩토링 작업 1차 완료
  src/components/PostDetail.jsx
  src/components/PostEditor.jsx
  src/components/PostForm.jsx
  src/hooks/useBoard.js
  src/hooks/useDeletePost.js
  src/hooks/useEditPost.js
  src/hooks/useNoticeEditPost.js
  src/hooks/usePagination.js
  src/hooks/usePostEditor.js
  src/hooks/useProductModal.js
  src/hooks/useSearchParams.js
  src/pages/comment/CommentList.jsx
  src/pages/comment/CommentListItem.jsx
  src/pages/comment/CommentNew.jsx
  src/pages/notice/NoticeEditPostPage.jsx
  src/pages/notice/NoticeListItem.jsx
  src/pages/notice/NoticeListPage.jsx
  src/pages/notice/NoticeNewPostPage.jsx
  src/pages/notice/NoticePostDetailPage.jsx
  src/pages/qna/QnAEditPostPage.jsx
  src/pages/qna/QnAListItem.jsx
  src/pages/qna/QnAListPage.jsx
  src/pages/qna/QnANewPostPage.jsx
  src/pages/qna/QnAPostDetailPage.jsx
  src/pages/qna/QnAProductModal.jsx
  src/store/qnaProductSearchStore.js
  src/utils/dateUtils.js
  src/utils/imageUpload.js
  src/utils/postAlerts.js
  src/utils/sortUtils.js
Labels: refactor

#134 메인화면 최종점검 및 라우트 분리화 작업
  src/components/layouts/index.jsx
  src/pages/MainProducts.jsx
  src/routes/eventRoutes.jsx
  src/routes/homeRoutes.jsx
  src/routes/noticeRoutes.jsx
  src/routes/qnaRoutes.jsx
  src/routes/shopRoutes.jsx
  src/routes/tansoRoutes.jsx
  src/routes/userRoutes.jsx
Labels: bug

#135 Q&A 게시판 목록 번호 순서 오류 해결
  src/pages/qna/QnAListItem.jsx
  src/pages/qna/QnAListPage.jsx
Labels: enhancement

#137 [Feature] 상세페이지 장바구니 상품 추가 기능 구현
  api/dbinit-sample/againSpring/data.js
  et --hard HEAD@{12}
  et --hard HEAD@{4}
  package-lock.json
  package.json
  public/images/pencildetail.jpg
  src/pages/Detail.jsx
  src/pages/ReviewItem.jsx
  src/pages/ReviewList.jsx
  src/store/cartStore.js
  src/store/useCartStore.js
Labels: feature

#142 탄소 발자국 추가기능 구현 - 페이지 UI 개선 및 데이터 연동
  api/dbinit-sample/againSpring/data.js
  src/hooks/useTanso.js
  src/pages/tanso/tanso-calc.jsx
  src/pages/tanso/tanso-intro.jsx
  src/pages/tanso/tanso-main.jsx
  src/routes/tansoRoutes.jsx
  src/store/tansoStore.js
Labels: feature, P3

#143 [Feature]상세페이지 리뷰 필터링 기능 구현
  src/pages/Cart.jsx
  src/pages/Detail.jsx
  src/pages/ReviewItem.jsx
  src/pages/ReviewList.jsx
  src/pages/WishList.jsx
  src/store/cartStore.js
  src/store/wishlistStore.js
Labels: feature

#148 [Feature]상세페이지 qna 필터링 기능 구현
  src/pages/Detail.jsx
  src/pages/qna/QnAListItem.jsx
Labels: feature

#146 탄소 발자국 메타 데이터 추가 / 헤더 메뉴 수정
  src/components/layouts/Menu.jsx
  src/pages/tanso/tanso-calc.jsx
  src/pages/tanso/tanso-intro.jsx
  src/pages/tanso/tanso-main.jsx
Labels: enhancement

#147 공지사항 Q&A 메타데이터 추가
  src/components/PostDetail.jsx
  src/pages/notice/NoticeEditPostPage.jsx
  src/pages/notice/NoticeListPage.jsx
  src/pages/notice/NoticeNewPostPage.jsx
  src/pages/notice/NoticePostDetailPage.jsx
  src/pages/qna/QnAEditPostPage.jsx
  src/pages/qna/QnAListPage.jsx
  src/pages/qna/QnANewPostPage.jsx
  src/pages/qna/QnAPostDetailPage.jsx
Labels: feature

#151 [FIX] Deploy Fail
  src/pages/user/Login.jsx
  src/pages/user/Signup.jsx
  src/pages/user/TermsOfService.jsx
  src/routes/userRoutes.jsx
Labels: bug

#155 🚑 [게시판_등록,수정] require is not defined 오류 해결
  src/components/PostEditor.jsx
  src/hooks/useEditPost.js
  src/hooks/usePostEditor.js
  src/pages/comment/CommentListItem.jsx
  src/pages/comment/CommentNew.jsx
  src/pages/eventPage/EventDetailPage.jsx
  src/pages/notice/NoticeEditPostPage.jsx
  src/pages/notice/NoticeListPage.jsx
  src/pages/notice/NoticeNewPostPage.jsx
  src/pages/notice/NoticePostDetailPage.jsx
  src/pages/qna/QnAEditPostPage.jsx
  src/pages/qna/QnAListPage.jsx
  src/pages/qna/QnANewPostPage.jsx
  src/pages/qna/QnAPostDetailPage.jsx
  src/utils/postAlerts.js
  vite.config.js
Labels: bug

#156 [FIX] 탄소발자국 페이지 / 검색기능 수정
  src/pages/searchPage.jsx
  src/pages/tanso/tanso-main.jsx
Labels: enhancement
